#!/usr/bin/env bash
# A rebuild script that commits on a successful build
set -e

pushd ~/dotfiles/nixos/
vim configuration.nix
alejandra . &>/dev/null
git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch &>nixos-switch.log || (cat nixos-switch.log | grep --color error && false)
current=$(nixos-rebuild list-generations | grep current)
git commit -am "$current"
popd
echo "NixOS Rebuilt OK!"